language: java

jdk:
  - oraclejdk8
  - openjdk7

before_deploy: >
  ant -f build/ant.xml
  
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: FgeOc773FTQrNg5tnlsrz8AKIQ3BkHoiMcfh02b+FcliZcUqdh0I9GVLcrboipBEZsll+w2raaT8YJQEpFafT4OQQquprLnRB6fk/+vInrv4Jk52wCkN2hjj1dK3dJ+qZ8qF1iLVAwJCPcILtcuruzT6g1y3+7LTmUy7MvFxz9I=
  file:
    - build/target/cloudslang-cli/cslang-cli.zip
    - build/target/cloudslang-cli/cslang-cli.tar.gz
    - build/target/cslang-builder/cslang-builder.zip
  skip_cleanup: true
  on:
    repo: CloudSlang/cloud-slang
    tags: true
    jdk: openjdk7

after_success:
  - mvn cobertura:cobertura coveralls:report
