language: java

jdk:
  - oraclejdk8
  - openjdk7

before_deploy: >
  ant -f build/ant.xml
  
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: BVOVjvS46X2NAT4osXi9zghM6LZHtqH1dO9GvUyIYRD+9XGosVbRPH75O/G5/GaDdfNcxb01Aaufu4kFAZXE26fCbp+xJAU0MsO0y3a+YNpEntn7a7BkvoqJ6ePcp3OMB485SsYpiy$
  file:
    - build/target/cloudslang-cli/cslang-cli.zip
    - build/target/cloudslang-cli/cslang-cli.tar.gz
    - build/target/cslang-builder/cslang-builder.zip
  skip_cleanup: true
  on:
    repo: CloudSlang/cloud-slang
    tags: true
    branch: master
    jdk: openjdk7

after_success:
  - mvn cobertura:cobertura coveralls:report
